### ISSUE TITLE
Records List

### ISSUE THREAD

**Issue by vindzhev** [vindzhev/Pacman#1]
Да се направи лист с най - добрите резултати. Да чете и пише в *.txt файл

**Comment by tkutsarov** [comment]
Добре, кой го взима да не се дублираме. Аз сложих звука днес. Ако някой от другите двама няма да почне листа с резултатите, мога аз да го направя? 

     On Wednesday, January 28, 2015 8:15 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 Да се направи лист с най - добрите резултати. Да чете и пише в *.txt файл—

**Comment by vindzhev** [comment]
Добре. Ако искаш го започни. Аз ще измисля как да направя да се стартира една форма, преди да започне играта, в която може да си въведеш някакъв Nickname, който после ще поставяме в списъла с топ резултатите

**Comment by tkutsarov** [comment]
ок, почвам го в нов клас, за да се добави после. Днес ще гледам да го завърша и да го кача, но може да не успея да дойда на лекцията. 

     On Thursday, January 29, 2015 12:05 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 Добре. Ако искаш го започни. Аз ще измисля как да направя да се стартира една форма, преди да започне играта, в която може да си въведеш някакъв Nickname, който после ще поставяме в списъла с топ резултатите—

**Comment by vindzhev** [comment]
Няма проблеи. Аз още не мога да разбера защо тези библиотеки правят проблем

**Comment by vindzhev** [comment]
При теб аудиото работи ли?

2015-01-29 12:48 GMT+02:00 Vasil Indzhev <v.indzhev@gmail.com>:

> Няма проблеи. Аз още не мога да разбера защо тези библиотеки правят проблем
>

**Comment by tkutsarov** [comment]
Да, тествах го многократно. Повтаря една и съща кратка мелодия, докато не свърши играта. Сега правя таблица с резултатите. 

     On Thursday, January 29, 2015 12:48 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 При теб аудиото работи ли?

2015-01-29 12:48 GMT+02:00 Vasil Indzhev <v.indzhev@gmail.com>:

**Comment by vindzhev** [comment]
Оправих аудиото. Сега пуска различни неща когато започва играта, когато се движи и когато умре

**Comment by Todorov96** [comment]
Здравейте и извинете, но имах работа през деня.Искам да ви попитам какви други идеи имате, с които мога да се заема и ако нямате да добавя ли бутони за рестартиране на играта,когато загубим.






 -------- Оригинално писмо --------

От: Vasil Indzhev notifications@github.com

Относно: Re: [Pacman] Records List (#1)

До: vindzhev/Pacman  

Изпратено на: 29.01.2015 13:56



 
 
  
Оправих аудиото. Сега пуска различни неща когато започва играта, когато се движи и когато умре

**Comment by vindzhev** [comment]
Здрасти!
Занимава ли ти се да правиш карти (нива) за играта? Ако искаш виж текстовия
файл -maze.txt и може да направиш рзлични конфигурации на пътища, положение
на хапчетата и т.н . Само имай едно на ум, че пътя, където може да ходи
човечето е обозначава с 1. С 2 са малките хапчета, 3 е хапчето, с което
замръзват всички призръцци, с 6 са всички пресечени пътища, защотото спрямо
6 всеки призрък си избира къде да ходи. Стартовата позиция на Pacman e Р, а
на призръците G. Кажи дали искаш да се заемеш с това, за да направя един
Issue в Git и да ти го сложа на профила.
На Thu Jan 29 2015 at 17:37:25 Todorov96 <notifications@github.com> написа:

**Comment by tkutsarov** [comment]
Добре. Аз качих клас, който чете, добавя, сортира и пише в текстови файл. Липсва връзката с основното приложение на играта и трябва да се направи поле след като приключи играта, където потребителя да въвежда името си, за да може след това да се добави към списъка. Класът с новата функционалност работи без проблеми отделно, но нещо не се получава като го добавя в проекта. Ще се пробвам да го довърша при първа възможност. Колко карти смяташ да имаме? 

     On Thursday, January 29, 2015 6:10 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 Здрасти!
Занимава ли ти се да правиш карти (нива) за играта? Ако искаш виж текстовия
файл -maze.txt и може да направиш рзлични конфигурации на пътища, положение
на хапчетата и т.н . Само имай едно на ум, че пътя, където може да ходи
човечето е обозначава с 1. С 2 са малките хапчета, 3 е хапчето, с което
замръзват всички призръцци, с 6 са всички пресечени пътища, защотото спрямо
6 всеки призрък си избира къде да ходи. Стартовата позиция на Pacman e Р, а
на призръците G. Кажи дали искаш да се заемеш с това, за да направя един
Issue в Git и да ти го сложа на профила.
На Thu Jan 29 2015 at 17:37:25 Todorov96 <notifications@github.com> написа:

**Comment by vindzhev** [comment]
Аз се опитах да създам текстово поле след като свърши играа, но доста
проблеми има. Най - малкото - не работи :D Иначе мисля за не повече от 2 -
3 карти с тази, която имаме в момента


На Thu Jan 29 2015 at 18:17:04 Tsvetelin Kutsarov <notifications@github.com>
написа:

> Добре. Аз качих клас, който чете, добавя, сортира и пише в текстови файл.
> Липсва връзката с основното приложение на играта и трябва да се направи
> поле след като приключи играта, където потребителя да въвежда името си, за
> да може след това да се добави към списъка. Класът с новата функционалност
> работи без проблеми отделно, но нещо не се получава като го добавя в
> проекта. Ще се пробвам да го довърша при първа възможност. Колко карти
> смяташ да имаме?
>
> On Thursday, January 29, 2015 6:10 PM, Vasil Indzhev <

**Comment by Todorov96** [comment]
Добре, ще направя няколко карти.






 -------- Оригинално писмо --------

От: Vasil Indzhev notifications@github.com

Относно: Re: [Pacman] Records List (#1)

До: vindzhev/Pacman  

Изпратено на: 29.01.2015 18:10



 
 
  Здрасти! 
  
 Занимава ли ти се да правиш карти (нива) за играта? Ако искаш виж текстовия 
  
 файл -maze.txt и може да направиш рзлични конфигурации на пътища, положение 
  
 на хапчетата и т.н . Само имай едно на ум, че пътя, където може да ходи 
  
 човечето е обозначава с 1. С 2 са малките хапчета, 3 е хапчето, с което 
  
 замръзват всички призръцци, с 6 са всички пресечени пътища, защотото спрямо 
  
 6 всеки призрък си избира къде да ходи. Стартовата позиция на Pacman e Р, а 
  
 на призръците G. Кажи дали искаш да се заемеш с това, за да направя един 
  
 Issue в Git и да ти го сложа на профила. 
  
 На Thu Jan 29 2015 at 17:37:25 Todorov96   написа:

**Comment by vindzhev** [comment]
Ако искаш може да опиташ да направиш така, че пътя (част от него) да описва
SOFT UNI /Не е задължително, просто ми хрумна/


2015-01-29 18:26 GMT+02:00 Todorov96 <notifications@github.com>:

**Comment by tkutsarov** [comment]
ок, до утре ще кача още няколко карти. 

     On Thursday, January 29, 2015 6:21 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 Аз се опитах да създам текстово поле след като свърши играа, но доста
проблеми има. Най - малкото - не работи :D Иначе мисля за не повече от 2 -
3 карти с тази, която имаме в момента


На Thu Jan 29 2015 at 18:17:04 Tsvetelin Kutsarov <notifications@github.com>
написа:

> Добре. Аз качих клас, който чете, добавя, сортира и пише в текстови файл.
> Липсва връзката с основното приложение на играта и трябва да се направи
> поле след като приключи играта, където потребителя да въвежда името си, за
> да може след това да се добави към списъка. Класът с новата функционалност
> работи без проблеми отделно, но нещо не се получава като го добавя в
> проекта. Ще се пробвам да го довърша при първа възможност. Колко карти
> смяташ да имаме?
>
> On Thursday, January 29, 2015 6:10 PM, Vasil Indzhev <

**Comment by tkutsarov** [comment]
Добра идея, Ще се пробвам. 

     On Thursday, January 29, 2015 6:38 PM, Tsvetelin Kutsarov <tkutsarov@yahoo.com> wrote:
   

 ок, до утре ще кача още няколко карти. 

     On Thursday, January 29, 2015 6:21 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 Аз се опитах да създам текстово поле след като свърши играа, но доста
проблеми има. Най - малкото - не работи :D Иначе мисля за не повече от 2 -
3 карти с тази, която имаме в момента


На Thu Jan 29 2015 at 18:17:04 Tsvetelin Kutsarov <notifications@github.com>
написа:

> Добре. Аз качих клас, който чете, добавя, сортира и пише в текстови файл.
> Липсва връзката с основното приложение на играта и трябва да се направи
> поле след като приключи играта, където потребителя да въвежда името си, за
> да може след това да се добави към списъка. Класът с новата функционалност
> работи без проблеми отделно, но нещо не се получава като го добавя в
> проекта. Ще се пробвам да го довърша при първа възможност. Колко карти
> смяташ да имаме?
>
> On Thursday, January 29, 2015 6:10 PM, Vasil Indzhev <
