### ISSUE TITLE
Mazes

### ISSUE THREAD

**Issue by vindzhev** [vindzhev/Pacman#2]
Катри в txt формат

**Comment by tkutsarov** [comment]
Пратих една maze2.txt Опитах се да направя надписа SOFT UNI с нулите, с пътищата трудно ще се получи. Би трябвало да изписва SOFT на горната третина от картата и UNI на долната или нещо подобно. 

     On Thursday, January 29, 2015 6:39 PM, Vasil Indzhev <notifications@github.com> wrote:
   

 Катри в txt формат—

**Comment by vindzhev** [comment]
Супер е! Утре сутрин, по време на Workshop - а, ще я нарисувам., Имаш ли
предпочитание за цветове?

На Thu Jan 29 2015 at 23:43:50 Tsvetelin Kutsarov <notifications@github.com>
написа:

> Пратих една maze2.txt Опитах се да направя надписа SOFT UNI с нулите, с
> пътищата трудно ще се получи. Би трябвало да изписва SOFT на горната
> третина от картата и UNI на долната или нещо подобно.
>
> On Thursday, January 29, 2015 6:39 PM, Vasil Indzhev <

**Comment by tkutsarov** [comment]
Не, както я направиш, ти решаваш. 

     On Friday, January 30, 2015 12:43 AM, Vasil Indzhev <notifications@github.com> wrote:
   

 Супер е! Утре сутрин, по време на Workshop - а, ще я нарисувам., Имаш ли
предпочитание за цветове?

На Thu Jan 29 2015 at 23:43:50 Tsvetelin Kutsarov <notifications@github.com>
написа:

> Пратих една maze2.txt Опитах се да направя надписа SOFT UNI с нулите, с
> пътищата трудно ще се получи. Би трябвало да изписва SOFT на горната
> третина от картата и UNI на долната или нещо подобно.
>
> On Thursday, January 29, 2015 6:39 PM, Vasil Indzhev <

**Comment by vindzhev** [comment]
Ето какво представлява. Доста пъгове излязоха с новата карта. Може да
пробвам да ги изчистя. Ако искате може да се откажем от допълнителните нива

2015-01-30 10:33 GMT+02:00 Tsvetelin Kutsarov <notifications@github.com>:

> Не, както я направиш, ти решаваш.
>
> On Friday, January 30, 2015 12:43 AM, Vasil Indzhev <

**Comment by tkutsarov** [comment]
Ако има много бъгове, няма да има смисъл от нови карти. Отнема доста време да се правят, ако ще трябва и да се чистят и бъгове още повече, така че по - добре да останем с основната. 

     On Friday, January 30, 2015 10:50 AM, Vasil Indzhev <notifications@github.com> wrote:
   

 Ето какво представлява. Доста пъгове излязоха с новата карта. Може да
пробвам да ги изчистя. Ако искате може да се откажем от допълнителните нива

2015-01-30 10:33 GMT+02:00 Tsvetelin Kutsarov <notifications@github.com>:

> Не, както я направиш, ти решаваш.
>
> On Friday, January 30, 2015 12:43 AM, Vasil Indzhev <

**Comment by vindzhev** [comment]
Задачата е говотова. Всичко е качено в GitHub. Смятам, че няма какво да
добавим. Пуснете си я, изиграйте 2 игри и я push - нете в Git - а.

На Fri Jan 30 2015 at 12:23:14 Tsvetelin Kutsarov <notifications@github.com>
написа:

> Ако има много бъгове, няма да има смисъл от нови карти. Отнема доста време
> да се правят, ако ще трябва и да се чистят и бъгове още повече, така че по
> - добре да останем с основната.
>
> On Friday, January 30, 2015 10:50 AM, Vasil Indzhev <

**Comment by tkutsarov** [comment]
Работи идеално. Виждам, че си оправил и резултатите. При оценяването на съотборниците ще имаш максимално възможна оценка от мен. Общо взето ти направи всичко по играта. Някой от другите двама колеги има ли участие, т.к. аз нямах мейли от тях относно самата игра и не видях да имат записи в github? На теб писали ли са ти и помагали ли са ти с играта?

**Comment by vindzhev** [comment]
Бяхме само аз и ти. Третият колега пита дали има да се прави нещо, но беше
вчера, по време на турнира по тенис на маса. Четвъртият дори не е питал
дали има да се прави нещо, дори не даде Username за GitHub - а

На Sun Feb 01 2015 at 13:30:18 Tsvetelin Kutsarov <notifications@github.com>
написа:
